# Generated by Django 4.0.6 on 2022-07-19 11:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Registeruser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact', models.CharField(blank=True, max_length=30, null=True)),
                ('token', models.CharField(max_length=100, null=True)),
                ('is_verified', models.BooleanField(default=False)),
                ('image', models.FileField(blank=True, upload_to='users')),
                ('otp', models.CharField(max_length=50, null=True)),
                ('connect', models.CharField(max_length=50, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
